plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '2.2.0'
}

repositories {
    // mavenLocal()
    mavenCentral()
    maven {
        name = "GitHubPackages"
        url = uri("https://maven.pkg.github.com/Ingenieria-en-sistemas-2025/PrintScriptV1")
        credentials {
            username = findProperty("gpr.user") ?: System.getenv("USERNAME")
            password = findProperty("gpr.key")  ?: System.getenv("TOKEN")
        }
    }
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
}
def psver = '1.0.1'

dependencies {
    implementation("org.printscript:runner:$psver")
    implementation("org.printscript:common:$psver")
    implementation("org.printscript:token:$psver")
    implementation("org.printscript:ast:$psver")
    implementation("org.printscript:lexer:$psver")
    implementation("org.printscript:parser:$psver")
    implementation("org.printscript:analyzer:$psver")
    implementation("org.printscript:formatter:$psver")
    implementation("org.printscript:interpreter:$psver")

    testImplementation 'junit:junit:4.13.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

test {
    minHeapSize = "8m"
    maxHeapSize = "8m"

    environment "BEST_FOOTBALL_CLUB", "San Lorenzo"

    // Run tests sequentially
    systemProperty 'junit.jupiter.execution.parallel.enabled', 'false'

    useJUnit()
}


