plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '2.2.0'
}

repositories {
    mavenLocal()
    mavenCentral()
// TODO: uncomment to be able to fetch packages in your own repository
//    maven {
//        name = "GitHubPackages"
//        url = uri("https://maven.pkg.github.com/<your-username>/printscript")
//        credentials {
//            username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
//            password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
//        }
//    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    minHeapSize = "5m" // initial heap size
    maxHeapSize = "7m" // maximum heap size
}

dependencies {
    implementation 'org.printscript:common'
    implementation 'org.printscript:token'
    implementation 'org.printscript:lexer'
    implementation 'org.printscript:formatter'
    implementation 'org.printscript:analyzer'
    implementation 'org.printscript:parser'
    implementation 'org.printscript:ast'
    implementation 'org.printscript:interpreter'
    implementation 'org.printscript:runner'

    testImplementation 'junit:junit:4.13.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

test {
    environment "BEST_FOOTBALL_CLUB", "San Lorenzo"
    useJUnit()
}
