plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '2.2.0'
}

repositories {
    // mavenLocal()
    mavenCentral()
    maven {
        name = "GitHubPackages"
        url = uri("https://maven.pkg.github.com/Ingenieria-en-sistemas-2025/PrintScriptV1")
        credentials {
            username = findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
            password = findProperty("gpr.key")  ?: System.getenv("GITHUB_TOKEN")
        }
    }
}

java {
    toolchain { languageVersion = JavaLanguageVersion.of(21) }
}
def psver = '1.0.0-SNAPSHOT'

dependencies {
    implementation("org.printscript:runner:$psver") { changing = true }
    implementation("org.printscript:common:$psver") { changing = true }
    implementation("org.printscript:token:$psver") { changing = true }
    implementation("org.printscript:ast:$psver") { changing = true }
    implementation("org.printscript:lexer:$psver") { changing = true }
    implementation("org.printscript:parser:$psver") { changing = true }
    implementation("org.printscript:analyzer:$psver") { changing = true }
    implementation("org.printscript:formatter:$psver") { changing = true }
    implementation("org.printscript:interpreter:$psver") { changing = true }

    testImplementation 'junit:junit:4.13.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

test {
    environment "BEST_FOOTBALL_CLUB", "San Lorenzo"
    useJUnit()
    minHeapSize = "5m"
    maxHeapSize = "7m"
}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}


